- be/src/main/java/com/dd/blog/domain/user/user/entity/User.java
- be/src/main/java/com/dd/blog/domain/user/user/repository/UserRepository.java
- be/src/main/java/com/dd/blog/domain/user/user/service/AuthTokenService.java
- be/src/main/java/com/dd/blog/domain/user/user/service/UserService.java
- be/src/main/java/com/dd/blog/global/exception/ApiException.java
- be/src/main/java/com/dd/blog/global/exception/ErrorCode.java
- be/src/main/java/com/dd/blog/global/rq/Rq.java
- be/src/main/java/com/dd/blog/global/security/CustomAuthenticationFilter.java
- be/src/main/java/com/dd/blog/global/security/CustomUserDetailsService.java
- be/src/main/java/com/dd/blog/global/security/SecurityConfig.java
- be/src/main/java/com/dd/blog/global/security/SecurityUser.java
- be/src/main/java/com/dd/blog/global/utils/JwtUtil.java
🔗 #19 #20 
</br></br>
- JWT 세팅
- 로그인, 회원가입
</br></br>
✒️postman
</br></br>
> [FEAT] User - 로그인, 회원가입, JWT - #19 #20

- be/src/main/java/com/dd/blog/domain/post/post/dto/PostResponseDto.java
- be/src/main/java/com/dd/blog/global/security/SecurityConfig.java
- fe/src/app/page.tsx
🔗#63
</br></br>
.
✒️메인페이지에 있던 더미 게시글들 지우고 게시글 api 호출
</br></br>
.
✒️프론트+백엔드 연동
</br></br>
> [FEAT] FE - 메인페이지 게시글 api 호출

- be/src/main/java/com/dd/blog/domain/post/category/controller/ApiV1CategoryController.java
- be/src/main/java/com/dd/blog/domain/post/category/service/CategoryService.java
- be/src/main/java/com/dd/blog/domain/post/post/repository/PostRepository.java
- be/src/main/java/com/dd/blog/domain/post/post/service/PostService.java
---
---
</br>
</br>
</br></br>
---
.
</br>.
이슈 링크 달아주세요. 
🔗
- feature/#83
</br></br>
.
✒️
자유게시판, 정보공유게시판 - R 기능, FE까지 연동
</br></br>
.
✒️
</br></br>
> [FEAT] 자유게시판, 정보공유게시판 - R 기능, FE까지 연동

- fe/src/app/page.tsx
---
---
</br>
</br>
</br></br>
---
.
</br>.
이슈 링크 달아주세요. 
🔗
</br></br>
.
✒️
</br></br>
.
✒️
</br></br>
> [FEAT] FE 미반영 UPDATE

- be/src/main/java/com/dd/blog/domain/post/post/controller/ApiV1PostController.java
- be/src/main/java/com/dd/blog/domain/post/post/repository/PostRepository.java
- be/src/main/java/com/dd/blog/domain/post/post/service/PostService.java
- fe/src/app/page.tsx
---
---
</br>
</br>
</br></br>
---
.
</br>.
이슈 링크 달아주세요. 
🔗
- feature/#71
</br></br>
.
✒️
게시판 - 검색 기능 구현 & UI
</br></br>
.
✒️
</br></br>
> [FEATURE] 게시판 - 검색 기능 구현 & UI

- be/src/main/java/com/dd/blog/domain/post/post/entity/Post.java
- be/src/main/java/com/dd/blog/domain/post/postlike/controller/ApiV1PostLikeController.java
- be/src/main/java/com/dd/blog/domain/post/postlike/service/PostLikeService.java
- fe/src/app/page.tsx
- fe/src/components/Post.tsx
---
---
</br>
</br>
</br></br>
---
.
</br>.
이슈 링크 달아주세요. 
🔗
- feature/#74
</br></br>
.
✒️
게시글 - 좋아요 기능 구현 및 FE
</br></br>
.
✒️
</br></br>
> [FEATURE] 게시글 - 좋아요 기능 구현 및 FE

- be/src/main/java/com/dd/blog/domain/admin/controller/AdminUserController.java
- be/src/main/java/com/dd/blog/domain/point/listener/PostEventListener.java
- be/src/main/resources/application.yml
- fe/src/app/admin/users/[userId]/page.tsx
이슈 링크 달아주세요. 
🔗
</br> #80 </br>
.
✒️
</br>
[FIX] 포인트 적립기능 및 관리자용 사용자 포인트 조회 기능 수정
</br>
.
어떻게 테스트했는지 (경로, 사용 조건 등)
직접 웹페이지에서 테스트 & postman 활용 
✒️
</br></br>
> [FIX] 포인트 적립기능 및 관리자용 사용자 포인트 조회 기능 수정

- be/src/main/java/com/dd/blog/domain/post/post/controller/ApiV1PostController.java
- be/src/main/java/com/dd/blog/domain/post/post/repository/PostRepository.java
- be/src/main/java/com/dd/blog/domain/post/post/service/PostService.java
- be/src/main/java/com/dd/blog/global/security/SecurityConfig.java
- fe/src/app/layout.tsx
- fe/src/app/page.tsx
- fe/src/components/ClientLayout.tsx
이슈 링크 달아주세요. 
🔗#79
</br></br>
.
✒️프론트엔드, 백엔드 무한스크롤 기능 추가
✒️쿼리를 이용해 상태 관리 하도록 메인 페이지 구조 변경
.
✒️로컬 테스트
</br></br>
> [FEAT] FE, BE - 무한스크롤 기능 추가, 쿼리 상태 관리

- be/src/main/java/com/dd/blog/domain/post/post/controller/ApiV1PostController.java
- fe/src/app/page.tsx
- fe/src/components/Post.tsx
---
---
</br>
</br>
</br></br>
---
.
</br>.
이슈 링크 달아주세요. 
🔗
- #92
</br></br>
.
✒️
- 게시글 - 삭제(FE) 구현
- 전체 게시글 GET swagger 개선
</br></br>
.
✒️
</br></br>
> [FEATURE] 게시글 - 삭제(FE) 구현, 전체 게시글 GET swagger 개선

- fe/src/app/page.tsx
- fe/src/app/profile/me/edit/page.tsx
- fe/src/components/Post.tsx
🧠 Feature PR
새로운 기능을 추가하는 PR입니다.
📝 PR 제목 규칙
❝ [FEAT] 대상 - 추가 기능 - #이슈번호 ❞
✏️ 여기부터 써주시면 됩니다.
[FEAT] FE - 메인페이지 - 'Weekly Best'를 '인기글'로 변경, 좋아요 순으로 인기게시글 선정(좋아요 수 같으면 조회순으로 선정)
[FIX] FE - 메인페이지 - 한번 좋아요 누르면 계속 분홍색 하트로 표시되어야 하는데 한번 리다이렉트 되면 흰색 하트로 바뀌어있는 오류 수정
.
1️⃣관련 이슈
이슈 링크 달아주세요.
🔗
https://github.com/Dopamine-Detoxx/Brain-Cleaner/issues/107
.
2️⃣작업 내용
✒️
.
3️⃣테스트
[ ]안에 x를 넣으시면 체크가 됩니다.
로컬에서 테스트 완료 🧪🫧
✒️
> [feat] FE - 메인페이지 Best인기게시글 top.5

- fe/src/app/page.tsx
- fe/src/app/profile/me/edit/page.tsx
- fe/src/components/Post.tsx
🧠 Feature PR
새로운 기능을 추가하는 PR입니다.
📝 PR 제목 규칙
❝ [FEAT] 대상 - 추가 기능 - #이슈번호 ❞
✏️ 여기부터 써주시면 됩니다.
[FEAT] 메인페이지 - 사용자 닉네임/프사 누르면 프로필페이지로 이동, 프로필카드 정보 백 연결
.
1️⃣관련 이슈
이슈 링크 달아주세요.
🔗
[feature/https://github.com/Dopamine-Detoxx/Brain-Cleaner/issues/24
](https://github.com/Dopamine-Detoxx/Brain-Cleaner/issues/110)
.
2️⃣작업 내용
✒️
메인페이지 - 하드코딩된 사용자 정보 백엔드와 연결해서 실제 정보 띄우기
프로필페이지, 프로필수정페이지 - 배경이 검은색(투명색)으로 보이는 현상 해결 (흰색으로 명시해줌)
.
3️⃣테스트
[ ]안에 x를 넣으시면 체크가 됩니다.
로컬에서 테스트 완료 🧪🫧
✒️
> [feat] FE - 메인페이지 - 사용자 닉네임/프사 누르면 프로필페이지로 이동, 프로필카드 정보 백 연결]

- be/src/main/java/com/dd/blog/domain/post/comment/controller/ApiV1CommentController.java
- be/src/main/java/com/dd/blog/domain/post/comment/service/CommentService.java
- fe/src/app/page.tsx
- fe/src/components/Post.tsx
---
---
</br>
리팩터링 PR입니다. 
</br>
</br></br>
---
.
</br>.
🔗
- #116 
</br></br>
.
✒️
</br></br>
.
댓글 작성: [FE]에서 userId 넘기는 구조 TO [BE] @AuthenticationPrincipal로 받기
for 통일성, restful
✒️
</br></br>
> [REFACTOR] 댓글 작성: [FE]에서 userId 넘기는 구조 TO [BE] @AuthenticationPrincipal로 받기

- be/src/main/java/com/dd/blog/domain/post/verification/controller/ApiV1VerificationController.java
- be/src/main/java/com/dd/blog/domain/post/verification/repository/VerificationRepository.java
- be/src/main/java/com/dd/blog/domain/post/verification/service/VerificationService.java
- be/src/main/java/com/dd/blog/domain/user/user/entity/User.java
- fe/src/app/page.tsx
- fe/src/app/verification/write/page.tsx
이슈 링크 달아주세요. 
🔗#115
</br></br>
.
✒️이번 주 인증 현황 백엔드, 프론트(/src/app/page.tsx) 작업
✒️연속 인증 백엔드 작업
✒️연속 인증 프론트 메인페이지 프로필 카드만 반영
✒️프론트에서 인증 게시글 작성시 인증 생성 api 호출하는 부분 추가
</br></br>
.
✒️프론트, 백엔드 연동 로컬 테스트
</br></br>
> [feat] 프로필 카드 - 이번 주 인증 현황 / 연속 인증

- be/src/main/java/com/dd/blog/domain/post/post/entity/Post.java
- fe/src/app/page.tsx
---
---
</br>
리팩터링 PR입니다. 
</br>
</br></br>
---
.
</br>.
🔗#106
</br></br>
.
✒️메인 페이지 (FE) 스크롤 위치 변경
</br></br>
.
✒️ui 개선
</br></br>
> [REFACTOR] FE - 메인페이지 스크롤 UI 변경 - #106

- be/src/main/java/com/dd/blog/domain/post/post/service/PostService.java
- be/src/main/java/com/dd/blog/global/init/CategoryInitializer.java
- fe/src/app/page.tsx
- fe/src/app/post/write/page.tsx
이슈 링크 달아주세요. 
🔗
</br>#75</br>
.
✒️ 
</br>
공지사항 게시판 구현 (관리자만 작성 / 수정 / 삭제 가능)
</br>
.
✒️
</br>
직접 프론트에서 테스트
</br>
> [FEAT] 공지사항 게시판 구현

- be/build.gradle.kts
- be/src/main/java/com/dd/blog/global/aws/AmazonS3Controller.java
- be/src/main/java/com/dd/blog/global/aws/AwsS3Config.java
- be/src/main/java/com/dd/blog/global/aws/AwsS3Uploader.java
- be/src/main/java/com/dd/blog/global/exception/ErrorCode.java
- be/src/main/resources/application.yml
🧠 Feature PR
새로운 기능을 추가하는 PR입니다.
📝 PR 제목 규칙
❝ [FEAT] 대상 - 추가 기능 - #이슈번호 ❞
( 예: ❛ [FEAT] PostService - 게시글 생성 기능 추가 - https://github.com/Dopamine-Detoxx/Brain-Cleaner/issues/13 ❜ )
✒️
AmazonS3 설정파일만 추가
.
1️⃣관련 이슈
이슈 링크 달아주세요.
🔗
#72 
.
2️⃣작업 내용
✒️
.
BE
application.yml, build.gradle.kts, AmazonS3Controller, AwsS3Config, AwsS3Uploader, ErrorCode
.
3️⃣테스트
[ ]안에 x를 넣으시면 체크가 됩니다.
로컬에서 테스트 완료 🧪🫧
인텔리제이 빨간줄)
> [feat] AmazonS3 설정파일 추가

- be/src/main/java/com/dd/blog/domain/point/pointstore/controller/PointStoreController.java
- be/src/main/java/com/dd/blog/domain/point/pointstore/dto/PointItemPurchaseListDto.java
- be/src/main/java/com/dd/blog/domain/point/pointstore/dto/PointItemPurchaseRequestDto.java
- be/src/main/java/com/dd/blog/domain/point/pointstore/dto/PointItemPurchaseResultDto.java
- be/src/main/java/com/dd/blog/domain/point/pointstore/dto/PointItemResponseDto.java
- be/src/main/java/com/dd/blog/domain/point/pointstore/entity/PointItem.java
- be/src/main/java/com/dd/blog/domain/point/pointstore/entity/PointItemPurchase.java
- be/src/main/java/com/dd/blog/domain/point/pointstore/repository/PointItemPurchaseRepository.java
- be/src/main/java/com/dd/blog/domain/point/pointstore/repository/PointItemRepository.java
- be/src/main/java/com/dd/blog/domain/point/pointstore/service/PointStoreService.java
- be/src/main/java/com/dd/blog/global/init/PointItemInitializer.java
---
---
</br>
</br>
</br></br>
---
.
</br>.
이슈 링크 달아주세요. 
🔗
- #113 
</br></br>
.
✒️
🔗[ERD 추가](https://www.erdcloud.com/d/8uSc8nCKPtug8fTGM)
**1️⃣ 포인트 상점 아이템 목록 조회 (GET /items)**
→ 전체 상점 아이템 목록 조회
- PointStoreController.java
- PointItemRepository.java : 아이템 정보 조회
- PointItem.java
- PointItemResponseDto.java : 아이템 목록 응답 DTO
**2️⃣ 아이템 구매 (POST /purchase)**
→ 로그인 유저가 아이템 구매
→ 잔여 포인트 차감, 구매 이력 저장, 포인트 기록 저장
- PointStoreController.java
- PointStoreService.java : 구매 로직
- PointItemRepository.java : 아이템 정보 조회
- …
> [FEATURE] 포인트상점 BE 전체, PointItemInitializer로 데이터 대입

- be/src/main/java/com/dd/blog/domain/user/user/controller/ApiV1UserController.java
- be/src/main/java/com/dd/blog/domain/user/user/service/UserService.java
- be/src/main/java/com/dd/blog/global/security/SecurityConfig.java
- fe/package-lock.json
- fe/package.json
- fe/src/app/signup/page.tsx
---
</br>
리팩터링 PR입니다. 
</br>
</br></br>
---
.
</br>.
🔗#112
</br></br>
.
✒️백엔드 이메일, 닉네임 중복체크 추가
✒️프론트엔드 실시간 중복체크 하도록 변경
✒️비밀번호 강도 인디케이터 추가
</br></br>
.
✒️회원가입 UI 개선이 필요했고, 
회원가입 버튼을 누를 때 유효성/중복 체크 하기보다는 
실시간으로 체크하는게 사용자 경험 면에서 더 좋을거라 생각해서
</br></br>
> [REFACTOR] FE - 회원가입 실시간 중복체크 + 비밀번호 강도 인디케이터 - #112

- be/src/main/java/com/dd/blog/domain/post/post/controller/ApiV1PostController.java
- be/src/main/java/com/dd/blog/domain/post/post/entity/Post.java
- be/src/main/java/com/dd/blog/domain/post/post/service/PostService.java
- be/src/main/java/com/dd/blog/domain/user/user/controller/ApiV1UserController.java
- be/src/main/java/com/dd/blog/domain/user/user/service/UserService.java
- fe/next.config.ts
- fe/src/app/page.tsx
- fe/src/app/post/write/page.tsx
- fe/src/app/profile/[id]/page.tsx
- fe/src/app/profile/me/edit/page.tsx
- fe/src/app/profile/me/page.tsx
- fe/src/app/verification/write/page.tsx
- fe/src/components/CommentModal.tsx
- fe/src/components/Post.tsx
- fe/src/contexts/UserContext.tsx
🧠 Feature PR
새로운 기능을 추가하는 PR입니다.
📝 PR 제목 규칙
❝ [FEAT] 대상 - 추가 기능 - #이슈번호 ❞
✏️ 여기부터 써주시면 됩니다.
* AmazonS3로 이미지파일 업로드방식 변경  
* 프로필사진 업로드 
* 게시글 사진첨부기능(여러장 첨부는 아직x)
.
1️⃣관련 이슈
이슈 링크 달아주세요.
🔗
https://github.com/Dopamine-Detoxx/Brain-Cleaner/issues/72
.
2️⃣작업 내용
✒️ BE
* S3 업로드 방식 Post-ApiV1PostController, User-ApiV1UserController, UserService에 적용
* Post엔티티의 imageUrl 필드길이 변경 (이미지를 하나밖에 못받아오는 문제 해결방안)
* 사진 여러장 올릴 수 있는 기능 구현중(새로운 이슈에서 작업예정) 
✒️ FE
* 사진이 여러장 첨부된 게시글은 게시글 상세보기 모달에서 이미지 캐러셀 효과 적용 완료 
* 게시글 상세보기 모달에서 새로 추가된 댓글의 프로필사진이 적용되지 않는 문제 발생(새로운 이슈에서 작업예정)
.
3️⃣테스트
[ ]안에 x를 넣으시면 체크가 됩니다.
로컬에서 테스트 완료 🧪🫧
✒️
> [FEAT] BE&FE - AmazonS3 사진 업로드 기능(게시글에 사진 여러장 올릴 수 있게), FE - 프로필사진

- be/src/main/java/com/dd/blog/domain/post/comment/controller/ApiV1CommentController.java
- be/src/main/java/com/dd/blog/domain/post/post/controller/ApiV1PostController.java
- be/src/main/java/com/dd/blog/domain/post/post/dto/PostRequestDto.java
---
---
</br>
리팩터링 PR입니다. 
</br>
</br></br>
---
.
</br>.
🔗
- #111 
</br></br>
.
✒️
Swagger api - restful하게 변경
</br></br>
.
✒️
</br></br>
> [REFACTOR] commentcontroller, postcontroller api 리팩토링 완료

- be/src/main/java/com/dd/blog/domain/post/post/controller/ApiV1PostController.java
- fe/src/app/point-store/my-purchases/page.tsx
- fe/src/app/point-store/page.tsx
- fe/src/app/profile/page.tsx
- fe/src/types/pointStore.ts
- fe/src/utils/api/pointStore.ts
---
name: 🐞 Bugfix
---
</br>
버그 수정 PR입니다. 
</br>
</br></br>
---
.
</br>.
이슈 링크 달아주세요. 
🔗
</br></br>
.
어떤 문제가 있었는지
✒️
PostController.createPost() - 머지로 인한 오류 수정
</br></br>
.
어떻게 수정했는지
✒️
</br></br>
> [FIX] PostController.createPost() - 머지로 인한 오류 수정

- be/src/main/java/com/dd/blog/global/security/CustomAuthenticationFilter.java
- fe/src/components/Post.tsx
- fe/src/utils/emojiUtils.tsx
---
name: 🐞 Bugfix
---
</br>
버그 수정 PR입니다. 
</br>
</br></br>
---
.
</br>.
이슈 링크 달아주세요. 
🔗#147
</br></br>
.
어떤 문제가 있었는지
✒️로그아웃 상태에서 이모티콘 코드 렌더링 안되는 문제
</br></br>
.
어떻게 수정했는지
✒️emojiUtils 구조 수정, CustomAuthenticationFilter 수정 ("/api/v1/pointstore/items" 엔드포인트 추가)
</br></br>
> [FIX] FE - 로그아웃 상태에서 이모티콘 코드 렌더링 안되는 문제 해결 - #147

- be/src/main/java/com/dd/blog/domain/admin/dto/AdminReportDto.java
- be/src/main/java/com/dd/blog/domain/admin/service/AdminReportService.java
- be/src/main/java/com/dd/blog/domain/post/post/controller/ApiV1PostController.java
- be/src/main/java/com/dd/blog/domain/post/post/dto/PostPatchRequestDto.java
- be/src/main/java/com/dd/blog/domain/post/post/dto/PostRequestDto.java
- be/src/main/java/com/dd/blog/domain/post/post/dto/PostResponseDto.java
- be/src/main/java/com/dd/blog/domain/post/post/entity/Post.java
- be/src/main/java/com/dd/blog/domain/post/post/service/PostService.java
- be/src/main/java/com/dd/blog/domain/post/verification/service/VerificationService.java
- be/src/main/java/com/dd/blog/global/json/StringArrayConverter.java
- fe/next.config.js
- fe/src/app/post/write/page.tsx
- fe/src/app/profile/me/page.tsx
- fe/src/app/verification/write/page.tsx
- fe/src/components/CommentModal.tsx
- fe/src/components/Post.tsx
---
name: 🐞 Bugfix
---
</br>
버그 수정 PR입니다. 
</br>
✒️다중 이미지 업로드 처리
✒️이미지 중복업로드 해결
</br></br>
---
.
</br>.
이슈 링크 달아주세요. 
🔗 #124 
</br></br>
.
어떤 문제가 있었는지
✒️게시글 이미지 여러 장 첨부해서 업로드 하는 기능 
✒️여러장의 이미지가 첨부되면, 가장 마지막으로 첨부했던 사진이 중복해서 업로드 되는 문제 
</br></br>
.
어떻게 수정했는지
✒️여러 장 첨부를 해도 한장만 업로드 되는 문제 => 이미지를 한장씩 추가 할때마다 이미지 배열에 추가가 되는게 아니라 새로 덮여쓰여지고 있었다. 업로드 하고나면 가장 마지막에 추가한 사진만 보여지는 문제를, 배열을 덮어쓰는 게 아니라 새로 추가가 되도록 수정 
✒️로그를 살펴보니 images/와 post/에 사진이 모두 저장되는 문제가 있었고, 게시글 이미지는 images/에 저장된 후, 업로드 후 불러올 때 post/에서 한번 더 가져오고 있었다. => AwsS3에 저장되는 폴더(경로)를 post/로 통일
</br></br>
> [FIX] BE&FE - 게시글 - 사진 여러장 첨부 기능

- be/src/main/java/com/dd/blog/domain/post/postlike/controller/ApiV1PostLikeController.java
- be/src/main/java/com/dd/blog/domain/post/postlike/repository/PostLikeRepository.java
- be/src/main/java/com/dd/blog/domain/post/postlike/service/PostLikeService.java
- be/src/main/java/com/dd/blog/global/security/CustomAuthenticationFilter.java
- fe/src/app/page.tsx
- fe/src/components/Post.tsx
---
name: 🐞 Bugfix
---
</br>
버그 수정 PR입니다. 
</br>
</br></br>
---
.
</br>.
이슈 링크 달아주세요. 
🔗#129
</br></br>
.
어떤 문제가 있었는지
✒️새로고침하면 좋아요가 취소되는 문제
</br></br>
.
어떻게 수정했는지
✒️백엔드 PostLike 도메인 - 컨트롤러 수정
- "/{postId}/like/check" 엔드 포인트 추가
- 좋아요 추가/삭제: @AuthenticationPrincipal로 현재 로그인한 유저 id 받아오도록 수정 (원래 하드코딩된 유저 id를 쓰고있었음)
✒️백엔드 PostLike 도메인 - 서비스 수정
- checkLike 메소드 추가
✒️백엔드 PostLike 도메인 - 레포지토리 수정
- boolean existsByUserAndPost(User user, Post post); 추가
✒️프론트엔드 메인페이지 수정
- handleLike, handleUnlike 로직 수정
✒️프론트엔드 Post 컴포넌트 수정
</br></br>
> [FIX] 좋아요 - 새로고침하면 취소되는 문제 해결

- be/src/main/java/com/dd/blog/domain/post/post/service/PostService.java
이슈 링크 달아주세요. 
🔗
</br>#159</br>
.
어떤 문제가 있었는지
✒️
</br>자유게시판 글 작성이 안됨</br>
.
어떻게 수정했는지
✒️
</br>PostService 코드 일부 수정</br>
> [FIX] 자유 게시판 글 작성 안되는 문제 해결

- be/src/main/java/com/dd/blog/domain/post/post/controller/ApiV1PostController.java
- be/src/main/java/com/dd/blog/domain/post/post/repository/PostRepository.java
- be/src/main/java/com/dd/blog/domain/post/post/service/PostService.java
- fe/src/app/page.tsx
---
---
</br>
</br>
</br></br>
---
.
</br>.
이슈 링크 달아주세요. 
🔗#165
</br></br>
.
✒️메인페이지 - 팔로워게시판 추가
- 백엔드: 팔로워 게시글들 페이지로 받아오는 엔드포인트 추가
- 프론트엔드: 메인페이지 팔로워 게시판 추가, fetchPosts 수정
</br></br>
.
✒️로컬 프론트, 백엔드 연동 테스트
</br></br>
> [FEAT] 메인페이지 - 팔로워게시판 추가 - #165

- fe/src/app/profile/[id]/page.tsx
- fe/src/app/profile/me/edit/page.tsx
- fe/src/app/profile/me/page.tsx
---
---
</br>
</br>
</br></br>
---
.
</br>.
이슈 링크 달아주세요. 
🔗#174
</br></br>
.
✒️
프론트 - 프로필사진 미등록 사용자의 프로필이 프로필 조회 페이지, 프로필 수정페이지에서 X박스로 보이지 않도록 수정
</br></br>
.
</br></br>
> [feat] 프로필 상세 페이지 - 프로필 기본 이미지 설정

- be/src/main/java/com/dd/blog/domain/post/post/controller/ApiV1PostController.java
- be/src/main/java/com/dd/blog/domain/post/post/repository/PostRepository.java
- be/src/main/java/com/dd/blog/domain/post/post/service/PostService.java
- be/src/main/java/com/dd/blog/global/exception/ErrorCode.java
- fe/src/app/page.tsx
- fe/src/app/post/write/page.tsx
- fe/src/app/report/write/page.tsx
- fe/src/app/verification/write/page.tsx
- fe/src/components/ClientLayout.tsx
- fe/src/components/CommentModal.tsx
- fe/src/components/Post.tsx
---
---
</br>
리팩터링 PR입니다. 
</br>
</br></br>
---
.
</br>.
🔗#164
</br></br>
.
✒️게시글 - 일일 게시글 등록 제한 추가 (하루에 인증게시판 1개, 다른 게시판 10개 제한)
✒️프론트엔드- alert 메시지 toast로 변경
✒️게시글 등록됐을 때 메인페이지 프로필 카드에 포인트, 인증현황 새로고침해야지 업데이트 되던거 바로 반영되도록 수정
</br></br>
.
✒️우리 서비스로 인한 또 다른 도파민 중독을 방지하기 위해
✒️성공/오류 메시지 ui 개선을 위해 toast 설정
</br></br>
> [REFACTOR] 게시글 - 게시글 등록 제한 추가, alert 메세지 toast로 변경 - #164

- be/src/main/java/com/dd/blog/global/init/PointItemInitializer.java
---
---
</br>
</br>
</br></br>
---
.
</br>.
이슈 링크 달아주세요. 
🔗#162
</br></br>
.
✒️
- S3버킷에 기존 이모티콘 등록(콘솔에서 직접 입력)
- h2-console에서 image_url을 S3에 저장된 이미지 경로로 설정
- PointItemInitiallizer에서 S3이미지를 return하는 메서드 추가 
</br></br>
.
</br></br>
> [feat] 이모티콘 db 절대경로로 업로드, S3콘솔에 이모티콘 추가 완료

- fe/src/app/point-store/page.tsx
---
---
</br>
</br>
</br></br>
---
.
</br>.
이슈 링크 달아주세요. 
🔗#167
</br></br>
.
✒️
</br></br>
.
</br></br>
> [feat] 이모티콘 페이지 이모티콘 두개 보이는 현상 수정 

- fe/src/app/profile/[id]/page.tsx
- fe/src/app/profile/me/page.tsx
---
name: 🐞 Bugfix
---
</br>
버그 수정 PR입니다. 
</br>
✒️
</br></br>
---
.
</br>.
이슈 링크 달아주세요. 
🔗 #182 
</br></br>
.
어떤 문제가 있었는지
✒️내 프로필페이지, 다른사람 프로필페이지에 들어가면
Console Error
An empty string ("") was passed to the src attribute. This may cause the browser to download the whole page again over the network. To fix this, either do not render the element at all or pass null to src instead of an
발생
-> 게시글 피드를 구성할 때 이미지가 첨부되지 않은 게시글의 이미지를 받아오려다 생긴 에러
</br></br>
.
어떻게 수정했는지
✒️게시글 피드를 구성할 때, 사진이 있는 게시글인지 없는 게시글인지 검사한 후 사진이 없는 게시글이면 사진이 들어가는 필드를 없앴다. 
</br></br>
> [FIX] FE - 프로필페이지 들어갈때 생기는 에러 해결

- fe/src/app/login/page.tsx
이슈 링크 달아주세요. 
🔗
</br>#181</br>
.
✒️
</br>정지된 계정으로 로그인 시, 정지된 계정임을 알려주는 문구 추가</br>
.
✒️
</br>프론트에서 확인</br>
> [feat] 정지된 계정으로 로그인 시, 정지된 계정임을 알려주는 문구 추가

- be/src/main/java/com/dd/blog/domain/user/follow/service/FollowService.java
- fe/src/app/profile/[id]/page.tsx
---
name: 🐞 Bugfix
---
</br>
버그 수정 PR입니다. 
</br>
✒️
</br></br>
---
.
</br>.
이슈 링크 달아주세요. 
🔗 #175 
</br></br>
.
어떤 문제가 있었는지
✒️이미 팔로우 하고있는 사용자 프로필 페이지에 여전히 '팔로우' 버튼이 뜸
✒️팔로워, 팔로잉을 눌러도 사용자 목록 모달이 나오지 않음 
✒️팔로워, 팔로잉 목록에 자기자신이 있음
</br></br>
.
어떻게 수정했는지
✒️BE
- FollowService에서 자기자신은 제외하는 코드 추가
✒️FE
- 팔로워, 팔로잉을 눌렀을 때 해당 사용자를 팔로우 하고있는 사용자, 팔로잉 하고있는 사용자 목록 모달 추가
- 팔로우버튼 새로고침해도 유지되도록 수정
</br></br>
> [fix] 팔로우버튼 새로고침 후에도 유지되도록 수정

- fe/src/app/page.tsx
- fe/src/components/CommentModal.tsx
- fe/src/components/Post.tsx
---
---
</br>
리팩터링 PR입니다. 
</br>
- **기본**
- **hover시**
</br></br>
---
.
</br>.
🔗#158
</br></br>
.
✒️
</br></br>
.
✒️
</br></br>
> [refactor] 댓글 "삭제" 쓰레기통 모양 아이콘 hover로 바꾸기

- fe/src/app/page.tsx
- fe/src/components/CommentModal.tsx
- fe/src/components/Post.tsx
---
---
</br>
리팩터링 PR입니다. 
</br>
</br></br>
---
.
</br>.
🔗#161
</br></br>
.
✒️프론트엔드 커스텀 색깔로 통일 
</br></br>
.
</br></br>
> [refactor] FE 핑크 고유색 통일

- be/src/main/java/com/dd/blog/domain/post/post/dto/PostResponseDto.java
- be/src/main/java/com/dd/blog/domain/post/post/service/PostService.java
- be/src/main/java/com/dd/blog/domain/post/verification/repository/VerificationRepository.java
- fe/src/app/page.tsx
- fe/src/components/Post.tsx
---
---
</br>
리팩터링 PR입니다. 
</br>
</br></br>
---
.
</br>.
🔗#188
</br></br>
.
✒️인증 게시글 상태에 따라 게시글 마크 바뀌도록
-> 메인페이지에서 유저 인증 게시글 상태(승인대기, 승인됨, 승인거부)를 직관적으로 볼 수 있도록 상태에 따른 아이콘을 렌더링 하도록 변경
</br></br>
.
✒️UX 개선
</br></br>
> [REFACTOR] 인증 게시글 상태에 따라 다른 아이콘을 렌더링 하도록 변경

- be/src/main/java/com/dd/blog/domain/post/post/controller/ApiV1PostController.java
- be/src/main/java/com/dd/blog/domain/post/post/repository/PostRepository.java
- be/src/main/java/com/dd/blog/domain/post/post/service/PostService.java
- fe/src/app/login/page.tsx
- fe/src/app/page.tsx
---
name: 🐞 Bugfix
---
</br>
버그 수정 PR입니다. 
</br>
</br></br>
---
.
</br>.
이슈 링크 달아주세요. 
🔗#198
</br></br>
.
어떤 문제가 있었는지
✒️메인페이지에서 인기순/최신순 정렬이 잘 되지 않던 문제
카테고리별 게시판 정렬이 안되는 문제가 또 생겨서 해결 
</br></br>
.
어떻게 수정했는지
✒️백엔드 Post 도메인 컨트롤러, 레포지토리, 서비스 sort 파라미터 받아오는 방식으로 수정
</br></br>
> [FIX] 메인페이지 정렬 안되는 문제 해결 - #198

- be/src/main/java/com/dd/blog/domain/post/post/service/PostService.java
- fe/src/components/CommentModal.tsx
- fe/src/components/Post.tsx
---
name: 🐞 Bugfix
---
</br>
버그 수정 PR입니다. 
</br>
</br></br>
---
.
</br>.
이슈 링크 달아주세요. 
🔗#199 
</br></br>
.
메인페이지 게시글 수정 - 인라인 방식으로 제목 따로, 내용 따로, 이미지 따로 수정하는 기능 에러
✒️
</br></br>
.
어떻게 수정했는지
✒️BE
- 제목, 내용, 이미지url을 한꺼번에 반환하지만 null값을 허용 
- PostService Update메소드에서 이미지 업로드 후에 새롭게 url 배열을 재구성하여 반환하도록 코드 수정
</br></br>
> [fix] 메인페이지 게시글(제목, 내용, 이미지) 수정 안되는 문제

- be/src/main/java/com/dd/blog/domain/user/user/repository/UserRepository.java
- be/src/main/java/com/dd/blog/global/init/AdminInitializer.java
- be/src/main/resources/application.yml
이슈 링크 달아주세요. 
🔗
</br>#181</br>
.
✒️
</br>[FEAT] 프로그램 실행 시 관리자 계정 자동 생성 Initializer 추가</br>
.
✒️
</br>직접 실행해서 확인</br>
> [FEAT] 프로그램 실행 시 관리자 계정 자동 생성 Initializer 추가

- be/src/main/java/com/dd/blog/global/security/SecurityConfig.java
- fe/.env.production
> ### `Preview` 탭을 누른 후 링크를 클릭하면 해당 템플릿으로 이동합니다. 
1️⃣ **`Preview`** 탭으로 이동해주세요. </br>
2️⃣ 👇 아래에서 **작업 종류에 맞는 템플릿을 클릭🖱️**해주세요!
</br>
</br></br>
[➡️ 기능 추가용 템플릿 선택](?expand=1&template=feature.md)
[➡️ 버그 수정용 템플릿 선택](?expand=1&template=bugfix.md)
[➡️ 문서 수정용 템플릿 선택](?expand=1&template=docs.md)
[➡️ 리팩토링 템플릿 선택](?expand=1&template=refactor.md)
[➡️ 핫픽스 템플릿 선택](?expand=1&template=hotfix.md)
</br></br></br>
> [FIX] 배포 환경 cors 설정
